# -- Main Menu --
# Simplified Chinese navigation menu

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 10

[[main]]
  name = "笔记"
  weight = 20

[[main]]
  name = "词"
  parent = "笔记"
  pageRef = "ci"
  weight = 10

[[main]]
  name = "简历"
  pageRef = "resume"
  weight = 30
